image: "artifactory-gojek.golabs.io:6555/cx-ziggurat:latest"

variables:
  PACKAGE_VERSION_FILE: "version.txt"
  APP_BASE_DOCKER_IMAGE: "artifactory-gojek.golabs.io:6555/app-clojure:2.7.1"
  APP_TYPE: "clojure"
  ACTOR_NAME: roomie

stages:
  - test
  - build
  - package
  - deploy-integration
  - deploy-production

cache:
  paths:
    - ~/.m2/
  key: "$CI_BUILD_REF_NAME"

test:
 stage: test
 services:
   - name: rabbitmq:latest
 script:
    - mv -fv resources/config.test.{ci.edn,edn}
    - lein test

build:
  stage: build
  script:
    - lein clean
    - lein uberjar
    - env > $PACKAGE_VERSION_FILE
    - mkdir -p pkg
    - cp ./target/${CI_PROJECT_NAME}.jar ./pkg/

  allow_failure: false
  artifacts:
    name: "${CI_PROJECT_NAME}-${APP_VERSION}-${CI_BUILD_REF}"
    paths:
      - ./pkg
      - ./$PACKAGE_VERSION_FILE
    expire_in: 1 week

package:
  stage: package
  variables:
    OVERRIDE_CI_PROJECT_NAME: roomie
  script:
    - package
  only:
    - master
    - tags
  tags:
    - package

deploy-integration:
  image: "artifactory-gojek.golabs.io:6555/cx-lambda:latest"
  stage: deploy-integration
  variables:
    DEPLOYMENT_ENVIRONMENT: integration
  environment:
    name: $DEPLOYMENT_ENVIRONMENT
  script:
    - deploy_lambda_actor
  only:
    - master
    - tags

deploy-production:
  image: "artifactory-gojek.golabs.io:6555/cx-lambda:latest"
  stage: deploy-production
  variables:
    DEPLOYMENT_ENVIRONMENT: production
  environment:
    name: $DEPLOYMENT_ENVIRONMENT
  script:
    - deploy_lambda_actor
  only:
    - tags
  when: manual
